  GNU nano 4.8                                                      docker-compose.yml                                                                 
version: "3.6"
x-chainlink-def:
  &chainlink-def
  # image: smartcontract/chainlink:latest
  image: agoric/chainlink:hacktheorb
  restart: on-failure
  secrets:
    - node_password
    - apicredentials
  env_file:
    - ./chainlink.env
  command: 'node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials'
x-postgres-def:
  &postgres-def
  image: agoric/postgres:hacktheorb
  restart: on-failure
  environment:
    - "POSTGRES_MULTIPLE_DATABASES=chainlink,ei"
    - "POSTGRES_HOST_AUTH_METHOD=trust"
x-ag-solo-node-def:
  &ag-solo-node-def
  image: agoric/cosmic-swingset-solo:${SDK_TAG:-latest}
  restart: on-failure
x-external-initiator-def:
  &external-initiator-def
  # image: smartcontract/external-initiator
  image: agoric/chainlink-external-initiator:latest
x-agoric-adapter-def:
  &agoric-adapter-def
  # image: smartcontract/agoric-adapter
  image: agoric/chainlink-adapter:latest
  restart: on-failure
  env_file:
    - ./adapter.env
services:
  chainlink-node:
    <<: *chainlink-def
    depends_on:
      - postgres-node
    ports:
      - "6691:6688"
    environment:
      - "DATABASE_URL=postgresql://chainlink@chainlink-agoric_postgres-node_1:5432/chainlink?sslmode=disable"
    volumes:
      - 'cl1:/chainlink'
  postgres-node:
    <<: *postgres-def
    volumes:
      - './docker-init-scripts:/docker-entrypoint-initdb.d'
      - 'pg1:/var/lib/postgresql/data'
  ag-solo-node:
    <<: *ag-solo-node-def
    ports:
      - "0.0.0.0:6891:6891"
    command: 'setup --webport=6891 --webhost=0.0.0.0 --netconfig=${AG_NETWORK_CONFIG}'
    environment:
      - "AG_SOLO_BASEDIR=chainlink"
      - "AG_NETWORK_CONFIG=${AG_NETWORK_CONFIG}"
      - "DEBUG=SwingSet:vat,SwingSet:ls"
    volumes:
      - 'ag1:/usr/src/app/solo'
      - '$HOME/.agoric:/root/.agoric'
      - '..:/usr/src/dapp-oracle'
  external-initiator-node:
    <<: *external-initiator-def
    depends_on:
      - ag-solo-node
      - postgres-node
    environment:
      - "EI_DATABASEURL=postgresql://ei@chainlink-agoric_postgres-node_1:5432/ei?sslmode=disable"
      - "EI_CHAINLINKURL=http://chainlink-agoric_chainlink-node_1:6688/"
    command: '{\"name\":\"agoric-node\",\"type\":\"agoric\",\"url\":\"ws://chainlink-agoric_ag-solo-node_1:6891/api/oracle\"}'
    env_file:
      - ./external_initiator1.env
  agoric-adapter:
    <<: *agoric-adapter-def
    depends_on:
      - ag-solo-node
    environment:
      - "AG_SOLO_ORACLE_URL=http://chainlink-agoric_ag-solo-node_1:6891/api/oracle"
volumes:
  pg1:
  cl1:
  ag1:
secrets:
  node_password:
    file: ./secrets/password.txt
  apicredentials:
    file: ./secrets/apicredentials