version: "3.6"
x-chainlink-def:
  &chainlink-def
  # image: smartcontract/chainlink:latest
  image: public.ecr.aws/chainlink/chainlink:1.3.0
  restart: always
  secrets:
    - node_password
    - apicredentials
  env_file:
    - ./chainlink.env
  command: 'node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials'
x-postgres-def:
  &postgres-def
  image: agoric/postgres:hacktheorb
  restart: on-failure
  environment:
    - "POSTGRES_MULTIPLE_DATABASES=chainlink,ei"
    - "POSTGRES_HOST_AUTH_METHOD=trust"
x-ag-solo-node-def:
  &ag-solo-node-def
  image: agoric/cosmic-swingset-solo:${SDK_TAG:-latest}
  restart: always
x-external-initiator-def:
  &external-initiator-def
  # image: smartcontract/external-initiator
  image: jacquesvcritien/agoric-cl-external-initiator:no-loop
x-agoric-adapter-def:
  &agoric-adapter-def
  image: jacquesvcritien/agoric-chainlink-external-adapter:v2
  restart: always
  env_file:
    - ./adapter.env
services:
  chainlink-node1:
    <<: *chainlink-def
    depends_on:
      - postgres-node1
    ports:
      - "6691:6688"
    environment:
      - "DATABASE_URL=postgresql://chainlink@chainlink-agoric_postgres-node1_1:5432/chainlink?sslmode=disable"
    volumes:
      - 'cl1:/chainlink'
  postgres-node1:
    <<: *postgres-def
    volumes:
      - './docker-init-scripts:/docker-entrypoint-initdb.d'
      - 'pg1:/var/lib/postgresql/data'
  ag-solo-node1:
    <<: *ag-solo-node-def
    ports:
      - "0.0.0.0:6891:6891"
    command: 'setup --webport=6891 --webhost=0.0.0.0 --netconfig=${AG_NETWORK_CONFIG}'
    environment:
      - "AG_SOLO_BASEDIR=chainlink"
      - "AG_NETWORK_CONFIG=${AG_NETWORK_CONFIG}"
      - "DEBUG=SwingSet:vat,SwingSet:ls"
      - "SOLO_SLOGFILE=/data/solo/solo.slog"
    volumes:
      - 'ag1:/usr/src/app/solo'
      - 'ag1:/data/solo'
      - '$HOME/.agoric:/root/.agoric'
      - '..:/usr/src/dapp-oracle'
  external-initiator-node1:
    <<: *external-initiator-def
    depends_on:
      - ag-solo-node1
      - postgres-node1
    environment:
      - "EI_DATABASEURL=postgresql://ei@chainlink-agoric_postgres-node1_1:5432/ei?sslmode=disable"
      - "EI_CHAINLINKURL=http://chainlink-agoric_chainlink-node1_1:6688/"
    command: '{\"name\":\"agoric-node\",\"type\":\"agoric\",\"url\":\"ws://chainlink-agoric_ag-solo-node1_1:6891/api/oracle\"} --cl_timeout=30s'
    env_file:
      - ./external_initiator1.env
  agoric-adapter1:
    <<: *agoric-adapter-def
    depends_on:
      - ag-solo-node1
    environment:
      - "AG_SOLO_ORACLE_URL=http://chainlink-agoric_ag-solo-node1_1:6891/api/oracle"
volumes:
  pg1:
  cl1:
  ag1:
secrets:
  node_password:
    file: ./secrets/password.txt
  apicredentials:
    file: ./secrets/apicredentials
